---
abstract: 'Files and code for building Perl 5.12.2'
author:
  - 'Curtis Jewell <CSJewell@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Dist-WiX-BuildPerl-5122
provides:
  Perl::Dist::WiX::BuildPerl::5122:
    file: lib/Perl/Dist/WiX/BuildPerl/5122.pm
    version: 1.250_100
requires:
  File::ShareDir: 1.02
  Moose::Role: 1.08
  Perl::Dist::WiX: 1.250_100
  perl: 5.010
resources:
  IRC: irc://irc.perl.org/#win32
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-WiX
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Dist-WiX-BuildPerl-5122/
version: 1.250_100
